encoding: utf-8
markdown: kramdown
highlighter: rouge
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: wzp's garden
#host: yourdomain.com
desc: Watering flowers in my own garden.

custom:
    category:
        default: 生活
        another: 学习
    categories:
      - name:  default
        title: 生活

      - name:  another
        title: 学习

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 王志鹏
        email: wzpfish@gmail.com
        disqus: ilovexztk                           # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: wzpfish                             # GitHub账号
        #gravatar: 1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
